apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terra.fullname" . }}-configmap
  namespace: terra{{ .Values.django.run_env }}
  labels:
{{ include "terra.fullname" . | indent 4 }}
data:
  DJANGO_RUN_ENV: {{ .Values.django.run_env }}
  DJANGO_DEBUG: {{ .Values.django.debug | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.django.allowed_hosts }}
  DJANGO_DB_ENGINE: django.db.backends.mysql
  DJANGO_DB_NAME: {{ .Values.django.db_name }}
  DJANGO_DB_USER: {{ .Values.django.db_user }}
  DJANGO_DB_HOST: {{ .Values.django.db_host }}
  DJANGO_DB_PORT: "3306"
  DJANGO_TEST_DB_NAME: {{ .Values.django.test_db_name }}
  DJANGO_EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
  DJANGO_EMAIL_HOST: {{ .Values.django.email_host }}
