apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "terra.fullname" . }}-externalsecret
  namespace: terra{{ .Values.django.env.run_env }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-failed
spec:
  backendType: {{ .Values.django.externalSecrets.backend | default "systemManager" | quote }}
  data:
    - key: {{ .Values.django.externalSecrets.env.django_secret_key }}
      name: "DJANGO_SECRET_KEY"
    - key: {{ .Values.django.externalSecrets.env.db_passwd }}
      name: "DJANGO_DB_PASSWD"