apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "clusterissuer.fullname" . }}
  labels:
    {{- include "clusterissuer.labels" . | nindent 4 }}
spec:
  backendType: {{ .Values.externalSecrets.backend | default "systemManager" | quote }}
  data:
    {{- range $k, $v := .Values.externalSecrets.env }}
    - key: {{ $v }}
      name: {{ $k }}
    {{- end }}
