{{ if .Values.externalSecrets.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
annotations:
  "helm.sh/hook": pre-install
metadata:
  name: {{ .Values.acme.eab.keySecretRef | default (printf "%s-eab" (include "clusterissuer.fullname" .)) | quote }}
  labels:
    {{- include "clusterissuer.labels" . | nindent 4 }}
spec:
  backendType: {{ .Values.externalSecrets.backend | default "systemManager" | quote }}
  data:
{{ toYaml .Values.externalSecrets.env | indent 4 }}
{{ end }}
