apiVersion: v1
kind: Service
metadata:
  name: {{ include "fester.fullname" . }}
  labels:
    {{- include "fester.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.fester.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "fester.selectorLabels" . | nindent 4 }}
