apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "qdb-cron.fullname" . }}
spec:
  schedule: "0 8 15 1-5,8-12 *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: qdb-reports
            image: uclalibrary/qdb-reports:latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: {{ include "qdb-cron.fullname" . }}-external
            - configMapRef:
                name: {{ include "qdb-cron.fullname" . }}-cm
            args:
            - /bin/bash
            - -c
            - python qdb/orchestrator.py
          restartPolicy: Never
      backoffLimit: 5
