apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "qdb-cron.fullname" . }}-external
spec:
  backendType: {{ .Values.qdbreports.externalSecrets.backend | default "systemManager" | quote }}
  data:
    {{- range $k, $v := .Values.qdbreports.externalSecrets.env }}
    - key: {{ $v }}
      name: {{ $k }}
    {{- end }}
