name: PR check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@d55017e2a0bd09ce86bd16fbb585fde9f77fe871
        with:
          version: v3.4.0

      - name: Add helm repository dependencies
        run: |
          find charts -maxdepth 1 -type d -exec helm dependency update {} \;

      - name: Lint helm charts
        run: |
          find charts -maxdepth 1 -type d -exec helm lint {} \;
