name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@d55017e2a0bd09ce86bd16fbb585fde9f77fe871
        with:
          version: v3.4.0

      - name: Add helm repository dependencies
        run: |
          for chartyaml in $(find charts -type f -name "Chart.yaml")
          do
            dependencies=$(cat ${chartyaml} | grep "repository: https" | awk '{print $2}' | xargs)
            subchart_root=$(echo ${chartyaml} | awk -F '[/]' '{print $1"/"$2}')
            if ! [ -z subcharts_with_dependencies ]; then
              for repo in ${dependencies}
              do
                helm repo add ${repo} ${repo}
                helm repo update
                helm dependency update ${subchart_root}
              done
            fi
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@120944e66390c2534cc1b3c62d7285ba7ff02594
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
