name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@d55017e2a0bd09ce86bd16fbb585fde9f77fe871
        with:
          version: v3.4.0

      - name: Add helm repository dependencies
        run: |
          find charts -type d -depth 1 -exec helm dependency update {} \;
          helm repo update

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@120944e66390c2534cc1b3c62d7285ba7ff02594
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
